spring:
  datasource:
    url: jdbc:postgresql://example.com/prod-db
    username: prod_user
    password: change-me
  jpa:
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: false
  sql:
    init:
      mode: never

actone:
  admin:
    purge-password: "prarambh-admin-delhi"
