spring:
  datasource:
    url: ${ACTONE_DB_URL:}
    username: ${ACTONE_DB_USERNAME:}
    password: ${ACTONE_DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: false
  sql:
    init:
      mode: never

actone:
  admin:
    purge-password: ${ACTONE_ADMIN_PASSWORD:}
