-- H2 schema for local development.
-- This exists solely to control physical column order, which Hibernate/JPA does not guarantee.

DROP TABLE IF EXISTS email_quote_selections;
DROP TABLE IF EXISTS tickets;
DROP TABLE IF EXISTS donations;

CREATE TABLE tickets (
  ticket_id UUID PRIMARY KEY,
  show_id VARCHAR(255),
  show_name VARCHAR(255) NOT NULL,
  full_name VARCHAR(255) NOT NULL,
  email VARCHAR(255),
  phone_number VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL,
  created_at_date DATE NOT NULL,
  created_at_time VARCHAR(16) NOT NULL,
  used_at_date DATE,
  used_at_time VARCHAR(16),
  qr_code_id VARCHAR(18) NOT NULL,
  ticket_count INT NOT NULL,
  customer_id INT,
  transaction_id VARCHAR(255),
  ticket_amount DECIMAL(10, 2) NOT NULL
);

CREATE TABLE email_quote_selections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id INT NOT NULL,
  email_type VARCHAR(16) NOT NULL,
  quote_key VARCHAR(64) NOT NULL,
  created_at_date DATE NOT NULL,
  created_at_time VARCHAR(32) NOT NULL,
  CONSTRAINT uk_quote_customer_type UNIQUE (customer_id, email_type)
);

-- Donations table used by the Donation API
CREATE TABLE donations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  serial_number VARCHAR(16) NOT NULL,
  full_name VARCHAR(255) NOT NULL,
  phone_number VARCHAR(255),
  email VARCHAR(255),
  message VARCHAR(1024),
  amount DECIMAL(12,2) NOT NULL,
  CONSTRAINT uk_donations_serial UNIQUE (serial_number)
);
