-- H2 schema for local development.
-- This exists solely to control physical column order, which Hibernate/JPA does not guarantee.

DROP TABLE IF EXISTS email_quote_selections;
DROP TABLE IF EXISTS tickets;
DROP TABLE IF EXISTS donations;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS feedback;
DROP TABLE IF EXISTS auditoriums;

CREATE TABLE tickets (
  ticket_id UUID PRIMARY KEY,
  show_id VARCHAR(255),
  show_name VARCHAR(255) NOT NULL,
  auditorium_id VARCHAR(64),
  full_name VARCHAR(255) NOT NULL,
  email VARCHAR(255),
  phone_number VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL,
  created_at_date DATE NOT NULL,
  created_at_time VARCHAR(16) NOT NULL,
  used_at_date DATE,
  used_at_time VARCHAR(16),
  qr_code_id VARCHAR(18) NOT NULL,
  ticket_count INT NOT NULL,
  user_id VARCHAR(32),
  transaction_id VARCHAR(255),
  ticket_amount DECIMAL(10, 2) NOT NULL
);

CREATE TABLE email_quote_selections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id VARCHAR(32) NOT NULL,
  email_type VARCHAR(16) NOT NULL,
  quote_key VARCHAR(64) NOT NULL,
  created_at_date DATE NOT NULL,
  created_at_time VARCHAR(32) NOT NULL,
  CONSTRAINT uk_quote_user_type UNIQUE (user_id, email_type)
);

-- Users table (durable buyer registry)
CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id VARCHAR(32) NOT NULL,
  full_name VARCHAR(255) NOT NULL,
  phone_number VARCHAR(20),
  email VARCHAR(255),
  created_at TIMESTAMP NOT NULL,
  CONSTRAINT uk_users_user_id UNIQUE (user_id),
  CONSTRAINT uk_users_identity UNIQUE (full_name, phone_number, email)
);

-- Donations table used by the Donation API
CREATE TABLE donations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  serial_number VARCHAR(16) NOT NULL,
  full_name VARCHAR(255) NOT NULL,
  phone_number VARCHAR(255),
  email VARCHAR(255),
  message VARCHAR(1024),
  transaction_id VARCHAR(255) NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_donations_serial UNIQUE (serial_number)
);

-- Feedback table (public submission, admin viewing)
CREATE TABLE feedback (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name VARCHAR(255) NOT NULL,
  phone_number VARCHAR(20),
  email VARCHAR(255),
  message VARCHAR(2048) NOT NULL,
  created_at TIMESTAMP NOT NULL
);

-- Auditorium seating state table
CREATE TABLE auditoriums (
  auditorium_id VARCHAR(64) PRIMARY KEY,
  auditorium_name VARCHAR(255) NOT NULL,
  show_id VARCHAR(255) NOT NULL,
  show_name VARCHAR(255) NOT NULL,
  show_date DATE NOT NULL,
  show_time TIME NOT NULL,
  ticket_amount DECIMAL(10,2) NOT NULL,
  total_seats INT NOT NULL,
  reserved_seats INT NOT NULL,
  booked_seats INT NOT NULL,
  confirmed_seats INT NOT NULL,
  checked_in_seats INT NOT NULL,
  available_seats INT NOT NULL
);
