-- Flyway migration for CockroachDB Cloud (PostgreSQL-compatible)
-- Creates the schema needed by the current JPA entities.

-- Cockroach recommends using STRING instead of VARCHAR, but PostgreSQL types work too.
-- We'll use standard PostgreSQL types for Hibernate compatibility.

CREATE TABLE IF NOT EXISTS tickets (
  ticket_id UUID PRIMARY KEY,

  show_id VARCHAR(255),
  show_name VARCHAR(255) NOT NULL,
  auditorium_id VARCHAR(255),

  full_name VARCHAR(255) NOT NULL,
  email VARCHAR(255),
  phone_number VARCHAR(255) NOT NULL,

  status VARCHAR(32) NOT NULL,

  created_at_date DATE NOT NULL,
  created_at_time VARCHAR(16) NOT NULL,

  used_at_date DATE,
  used_at_time VARCHAR(16),

  qr_code_id VARCHAR(18) NOT NULL,
  ticket_count INT4 NOT NULL DEFAULT 1,

  user_id VARCHAR(32),
  transaction_id VARCHAR(255),
  ticket_amount NUMERIC(10,2) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_tickets_user_id ON tickets (user_id);
CREATE INDEX IF NOT EXISTS idx_tickets_phone_number ON tickets (phone_number);
CREATE INDEX IF NOT EXISTS idx_tickets_show_id ON tickets (show_id);


CREATE TABLE IF NOT EXISTS users (
  id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id VARCHAR(32) NOT NULL UNIQUE,
  full_name VARCHAR(255) NOT NULL,
  phone_number VARCHAR(20),
  email VARCHAR(255),
  created_at TIMESTAMPTZ NOT NULL
);

-- Mirrors @UniqueConstraint(columnNames = {"full_name","phone_number","email"})
CREATE UNIQUE INDEX IF NOT EXISTS uk_users_full_phone_email ON users (full_name, phone_number, email);

CREATE INDEX IF NOT EXISTS idx_users_user_id ON users (user_id);


CREATE TABLE IF NOT EXISTS feedback (
  id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name VARCHAR(255) NOT NULL,
  phone_number VARCHAR(20),
  email VARCHAR(255),
  message VARCHAR(2048) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL
);


CREATE TABLE IF NOT EXISTS donations (
  id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  serial_number VARCHAR(32) NOT NULL UNIQUE,
  full_name VARCHAR(255) NOT NULL,
  phone_number VARCHAR(20),
  email VARCHAR(255),
  message VARCHAR(255),
  transaction_id VARCHAR(255) NOT NULL,
  amount NUMERIC(10,2) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_donations_serial_number ON donations (serial_number);


CREATE TABLE IF NOT EXISTS auditoriums (
  auditorium_id VARCHAR(64) PRIMARY KEY,
  auditorium_name VARCHAR(255) NOT NULL,
  show_id VARCHAR(255) NOT NULL,
  show_name VARCHAR(255) NOT NULL,
  show_date DATE NOT NULL,
  show_time TIME NOT NULL,

  total_seats INT4 NOT NULL,
  reserved_seats INT4 NOT NULL,
  booked_seats INT4 NOT NULL,
  confirmed_seats INT4 NOT NULL,
  checked_in_seats INT4 NOT NULL,
  available_seats INT4 NOT NULL,

  ticket_amount NUMERIC(10,2) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_auditoriums_show_id ON auditoriums (show_id);


CREATE TABLE IF NOT EXISTS email_quote_selections (
  id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id VARCHAR(32) NOT NULL,
  email_type VARCHAR(16) NOT NULL,
  quote_key VARCHAR(64) NOT NULL,
  created_at_date DATE NOT NULL,
  created_at_time TIME NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_quote_user_type ON email_quote_selections (user_id, email_type);

